Implements sdk
dnc-grafmen/ipay-sdk pull request #1
Opened 2022-06-21 16:54 UTC by dnc-grafmen

2022-06-22 14:21 UTC, jarviis101 requested changes

2022-06-22 14:21 UTC, jarviis101 commented on src/Factory/ConverterServiceFactory.php
> +        };
эксепшон общий

2022-06-22 14:21 UTC, jarviis101 commented on src/Factory/PaymentFactoryInterface.php
> +}
line

2022-06-22 14:21 UTC, jarviis101 commented on src/Factory/RefundFactory.php
> +        }
```suggestion
        if ($amount = $data->getAmount()) {
            $payment->addChild($this->factory->create('amount', $amount));
        }
```

2022-06-22 14:21 UTC, jarviis101 commented on src/Factory/RefundFactory.php
> +        }
выше написал

2022-06-22 14:21 UTC, jarviis101 commented on src/Generator/SaltGeneratorInterface.php
> +}
line

2022-06-22 14:21 UTC, jarviis101 commented on src/IPayClient.php
> +        }
Переброс, что бы что? И ловишь только GuzzleException
PaymentException - этот игнорится?

2022-06-22 14:21 UTC, jarviis101 commented on src/Service/ResponseTransformService.php
> +
`use function PHPUnit\Framework\assertTrue;` в проде не упадёт?

2022-06-26 18:45 UTC, dnc-grafmen commented on src/IPayClient.php
> +        }
Мне же не нужно в sdk как-то обрабатывать ошибки. Это дело для клиентского кода. Можно разве что преобразовать его во внутренний эксепшен

2022-06-26 19:21 UTC, dnc-grafmen commented on src/Factory/PaymentFactoryInterface.php
> +}
?

2022-06-26 19:34 UTC, merged